### YamlMime:PythonClass
uid: azure.mgmt.applicationinsights.v2015_05_01.models.AnnotationErrorException
name: AnnotationErrorException
fullName: azure.mgmt.applicationinsights.v2015_05_01.models.AnnotationErrorException
module: azure.mgmt.applicationinsights.v2015_05_01.models
inheritances:
- msrest.exceptions.HttpOperationError
summary: 'Server responsed with exception of type: ''AnnotationError''.'
constructor:
  syntax: AnnotationErrorException(deserialize, response, *args)
  parameters:
  - name: deserialize
    description: A deserializer
    isRequired: true
  - name: response
    description: Server response to be deserialized.
    isRequired: true
methods:
- uid: azure.mgmt.applicationinsights.v2015_05_01.models.AnnotationErrorException.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.mgmt.applicationinsights.v2015_05_01.models.AnnotationErrorException.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.mgmt.applicationinsights.v2015_05_01.models.AnnotationErrorException.args
  name: args
